name: Build and deploy JAR app to Azure Web App - BookStore-Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'target/SYSC4806_AmazinBookstore-1.0-SNAPSHOT.jar'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy to Azure Web App using zipDeploy
        run: |
          echo "Creating ZIP file for deployment..."
          Compress-Archive -Path 'SYSC4806_AmazinBookstore-1.0-SNAPSHOT.jar' -DestinationPath 'deployment.zip'
          echo "Deploying to Azure Web App..."
          az webapp deploy --resource-group BookStore-Resource --name BookStore-Application --src-path deployment.zip --type zip
